void *dummyArgv();
void *buildPss();
void *buildPssAntMap();
void *buildUeDownCoding(int i);
void *buildUeDownMod(int i);
void *buildUeDownAntMap(int i);
int64 keyPss();
int64 keyPssAntMap();
int64 keyUeDownCoding();
int64 keyUeDownMod();
int64 keyUeDownAntMap();
